version: '3.8'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php7
    networks:
      - backend

  php7:
    image: php:7.4-fpm
    volumes:
      - ./site:/srv
    networks:
      - backend

  php8:
    image: php:8.0-fpm
    volumes:
      - ./site:/srv
    networks:
      - backend

  php83:
    image: php:8.3-fpm
    volumes:
      - ./site:/srv
    networks:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:alpine
    networks:
      - backend

volumes:
  caddy_data:
  caddy_config:
  mysql_data:

networks:
  backend:
    driver: bridge
